export enum NotificationType {
  FEEDBACK = 'FEEDBACK',
  OFFER_JOB = 'OFFER_JOB',
  STRIKE = 'STIKES',
  ACEPTED_JOB = 'ACEPTED_JOB',
  FINISHED_ACEPTED = 'FINISHED_ACEPTED',
  VIEWS_PROFILE = 'VIEWS_PROFILE',
  VIEWS_PUBLICATION = 'VIEWS_PUBLICATION',
  POSIBLE_BLOCK = 'POSIBLE_BLOCK',
}
